### ISSUE TITLE
Roles should be fixed or abandoned

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/doc#1736]
At one time we needed to add special roles in conf.py
codenormal codebold codeitalic codebolditalic
because Sphinx had defects and bugs.
But at some point, I don't know when, the roles ceased to work.

For example, reference/configuration/index.rst has
"If the command to start Tarantool includes :codeitalic:`lua-initialization-file`, then"
but https://www.tarantool.io/en/doc/latest/reference/configuration/
does not have italics.

There are not many role uses, and the worst Sphinx problem is fixed:
one can now put :samp: and :code: together so that {}s can
be in italics. So probably we can remove role uses.

Additionally there are roles for colours: codegreen etc.
These roles also ceased to work.
But they are only used in tdb.rst, which recently was
https://github.com/tarantool/doc/commit/62e67ce321700e0684f0b1bc3d17622b540c7ff5
pushed out of the main section of the manual.
So I think it is not worth fixing.

So, unless somebody objects and says that we should fix the
problem, I will make small appropriate changes in a few days.
This affects our documentation guidelines.

**Comment by Totktonada** [comment]
I would vote for fixing. @NickVolynkin, what do you think?

**Comment by NickVolynkin** [comment]
Hi! Could we make a step back and determine why we need these roles and how we intend to use them (and have used them in the past)?

> but https://www.tarantool.io/en/doc/latest/reference/configuration/ does not have italics.

What's worse, it doesn't have inline code highlighting and looks just like plain text.

There's not much about these roles in [our documentation guidelines](https://www.tarantool.io/en/doc/latest/dev_guide/documentation_guidelines/). Looks like we made them to format code blocks manually by highlighting specific lines and words in them. Peter @pgulutzan, is that so? Could you please tell us more about the purpose of these roles?

**Comment by pgulutzan** [comment]
Answered by email with subject line = Issue#1736 Roles should be fixed or abandoned.

**Comment by NickVolynkin** [comment]
@pgulutzan thank you, I have received your email, will reply tomorrow.

**Comment by NickVolynkin** [comment]
About the roles not working: they actually do work on the Sphinx stage. The rST source in example:

```rst
If the command to start Tarantool includes :codeitalic:`lua-initialization-file`, then...
```

produces the following HTML:

```html
<p>If the command to start Tarantool includes <span class="ccodei">lua-initialization-file</span>, then...</p>
```

The problem is that the class `ccodei` isn't in the CSS anymore. We've lost it at some point and still can bring it back.

**Comment by NickVolynkin** [comment]
@pgulutzan This is a frontend issue, so I'm assigning it to Artem. We still have some usages of these roles, and we'll fix them. It is still an open question whether we should use them in the future; probably we shouldn't. The decision should go together with updating our contribution guide. I'll make a separate task for it.

**Comment by NickVolynkin** [comment]
@pgulutzan Artem fixed this a while ago, but we forgot to close this issue, so I'm doing it now. Thanks for reporting it!

**Comment by NickVolynkin** [comment]
Quick note: for emphasizing whole lines in a code snippet we can use `code-block` with [`:emphasize-lines:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-option-code-block-emphasize-lines) attribute.
